name = "mineops-production"
main = "api/worker.js"
compatibility_date = "2026-10-01"
assets = { directory = "public", binding = "ASSETS" }

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "mineops-production"
database_id = "6d232140-6224-45de-afec-4bc0bdb10b48"

[[r2_buckets]]
binding = "EVIDENCE_BUCKET"
bucket_name = "mineops-evidence"
